/*
 * File Name: VirtualGarageGUI.java
 * Author: Jonathan Ross Tew
 * Last Modified: 5/4/15
 * Purpose of implementation: This is the GUI class that holds all of the 
 * swing components for the JFrame. It also is where a majority of the methods
 * are implemented.
 */
package virtualGaragePackage;

import java.util.ArrayList;
import javax.swing.JOptionPane;

public class VirtualGarageGUI extends javax.swing.JFrame {

    // All the constructors and variables needed for the GUI:
    private MyTableModel myModel = new MyTableModel();
    private FileFacade fileFacade = new FileFacade();
    private AbstractTableFactory tableFactory = new TableFactory();
    private ArrayList holdingList = new ArrayList();
    private String currentUser = null;
    private String currentVehicle = null;
    private String curVehMake = null;
    private String curVehYear = null;
    private String[] vehicleList = null;
    private String[] userList = null;
    private String fileName = "default";

    /**
     * Creates new form VirtualGarageGUI
     */
    public VirtualGarageGUI() {
        // Create a list of users registered:
        userList = fileFacade.getUserList("userList");

        // Initialize the swing components:
        initComponents();

        // Populate username drop-down box:
        usernameCB.removeAllItems();
        for (int i = 0; i < userList.length; i++) {
            usernameCB.addItem(userList[i]);
        }
        
        // Hide appropiate panels
        loginPanel.setVisible(true);
        vehiclePanel.setVisible(false);
        maintenanceLogPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        maintenanceLogPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        maintTable = new javax.swing.JTable();
        dateTB = new javax.swing.JTextField();
        milesTB = new javax.swing.JTextField();
        maintTB = new javax.swing.JTextField();
        commentsTB = new javax.swing.JTextField();
        costTB = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        addRowButton = new javax.swing.JButton();
        clearTextButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        userTextField = new javax.swing.JTextField();
        makeTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        maintLogOutButton = new javax.swing.JButton();
        backGarageButton = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameCB = new javax.swing.JComboBox();
        passwordTB = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        newUsernameTB = new javax.swing.JTextField();
        newPasswordTB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createNewUserButton = new javax.swing.JButton();
        vehiclePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        vehicleCB = new javax.swing.JComboBox();
        goToLogButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        newMakeTB = new javax.swing.JTextField();
        newModelTB = new javax.swing.JTextField();
        newYearTB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        createNewVehicleButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        vehicleLogOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virtual Garage");
        setMaximumSize(new java.awt.Dimension(1400, 700));
        setMinimumSize(new java.awt.Dimension(1400, 700));
        setName("vgFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1400, 700));

        maintTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(maintTable);

        jLabel15.setText("Date:");

        jLabel16.setText("Mileage:");

        jLabel17.setText("Maintenance Performed:");

        jLabel18.setText("Comments:");

        jLabel19.setText("Cost:");

        addRowButton.setText("Add New Row");
        addRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRowButtonActionPerformed(evt);
            }
        });

        clearTextButton.setText("Clear Text");
        clearTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTextButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save Table");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        userTextField.setEditable(false);

        makeTextField.setEditable(false);

        modelTextField.setEditable(false);

        yearTextField.setEditable(false);

        jLabel20.setText("Current User:");

        jLabel21.setText("Vehicle Make:");

        jLabel22.setText("Vehicle Model:");

        jLabel23.setText("Vehicle Year:");

        maintLogOutButton.setText("Log Out");
        maintLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintLogOutButtonActionPerformed(evt);
            }
        });

        backGarageButton.setText("Back to Garage");
        backGarageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backGarageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maintenanceLogPanelLayout = new javax.swing.GroupLayout(maintenanceLogPanel);
        maintenanceLogPanel.setLayout(maintenanceLogPanelLayout);
        maintenanceLogPanelLayout.setHorizontalGroup(
            maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceLogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1340, Short.MAX_VALUE)
                    .addGroup(maintenanceLogPanelLayout.createSequentialGroup()
                        .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(maintenanceLogPanelLayout.createSequentialGroup()
                                .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateTB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(milesTB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addComponent(addRowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(maintenanceLogPanelLayout.createSequentialGroup()
                                .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maintTB, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(commentsTB, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(maintenanceLogPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(costTB)))
                            .addGroup(maintenanceLogPanelLayout.createSequentialGroup()
                                .addComponent(clearTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(maintenanceLogPanelLayout.createSequentialGroup()
                        .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 618, Short.MAX_VALUE)
                        .addComponent(backGarageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maintLogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        maintenanceLogPanelLayout.setVerticalGroup(
            maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceLogPanelLayout.createSequentialGroup()
                .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maintenanceLogPanelLayout.createSequentialGroup()
                        .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(9, 9, 9)
                        .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(maintenanceLogPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maintLogOutButton)
                            .addComponent(backGarageButton))))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(milesTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commentsTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(maintenanceLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRowButton)
                    .addComponent(clearTextButton)
                    .addComponent(saveButton))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Welcome to the Virtual Garage Program");

        usernameCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("New User Creation:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("User Login:");

        jLabel6.setText("New Username:");

        jLabel7.setText("New Password:");

        createNewUserButton.setText("Create New User");
        createNewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(loginButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordTB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernameCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(newUsernameTB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(createNewUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(newPasswordTB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(608, 608, 608)
                                .addComponent(jLabel4)))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(167, 167, 167)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(newUsernameTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(newPasswordTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(createNewUserButton))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setText("Welcome to Your Virtual Garage");

        vehicleCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        goToLogButton.setText("Go To Maintenance Log");
        goToLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLogButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Vehicle:");

        jLabel10.setText("New Make:");

        jLabel11.setText("New Model:");

        jLabel12.setText("New Year:");

        createNewVehicleButton.setText("Create New Vehicle Log");
        createNewVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewVehicleButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("New Vehicle Log Creation:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Vehicle Selection:");

        vehicleLogOutButton.setText("Log Out");
        vehicleLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleLogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehiclePanelLayout = new javax.swing.GroupLayout(vehiclePanel);
        vehiclePanel.setLayout(vehiclePanelLayout);
        vehiclePanelLayout.setHorizontalGroup(
            vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vehiclePanelLayout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(vehiclePanelLayout.createSequentialGroup()
                                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(goToLogButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(vehicleCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(430, 430, 430)
                                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(10, 10, 10)
                                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newMakeTB, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(newModelTB)))))
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(367, 367, 367)
                        .addComponent(jLabel13))
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createNewVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newYearTB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(282, 282, 282))
            .addGroup(vehiclePanelLayout.createSequentialGroup()
                .addGap(642, 642, 642)
                .addComponent(vehicleLogOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vehiclePanelLayout.setVerticalGroup(
            vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiclePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel8)
                .addGap(127, 127, 127)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(newMakeTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goToLogButton)
                    .addComponent(newModelTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newYearTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(createNewVehicleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(vehicleLogOutButton)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(vehiclePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(maintenanceLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(vehiclePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(maintenanceLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(maintenanceLogPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(loginPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(vehiclePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // The login button checks the username/password combo, then takes 
        // the user to their virtual garage:
        String username = usernameCB.getSelectedItem().toString();
        String password = passwordTB.getText();
        // Check user/pass combo
        if (fileFacade.checkLogin("userList", username, password)) {
            currentUser = username;
            loginPanel.setVisible(false);
            vehiclePanel.setVisible(true);
            vehicleList = fileFacade.getUserVehicleList("vehicleList", currentUser);
            vehicleCB.removeAllItems();
            for (int i = 0; i < vehicleList.length; i++) {
                vehicleCB.addItem(vehicleList[i]);
            }
            passwordTB.setText("");
        } else {
            // Display message if login info is incorrect:
            JOptionPane.showMessageDialog(null, "Password incorrect. Please try again.");
            passwordTB.setText("");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void createNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewUserButtonActionPerformed
        // Method for when the create new user button is pressed. Adds the entered
        // username and password to the userList text file in the project files:
        if (newUsernameTB.getText().isEmpty() || newPasswordTB.getText().isEmpty()) {
            // Make sure both fields entered:
            JOptionPane.showMessageDialog(null, "Please enter both a Username and Password.");
        } else {
            String newUser = newUsernameTB.getText().toString();
            String newPass = newPasswordTB.getText().toString();
            String[] newUserRow = {newUser, newPass};

            fileFacade.writeNewUsers("userList", newUserRow);
            String[] tempUserList = fileFacade.getUserList("userList");
            usernameCB.removeAllItems();
            for (int i = 0; i < tempUserList.length; i++) {
                usernameCB.addItem(tempUserList[i]);
            }

            newUsernameTB.setText("");
            newPasswordTB.setText("");
        }
    }//GEN-LAST:event_createNewUserButtonActionPerformed

    private void goToLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLogButtonActionPerformed
        // This button takes the user to their maintenance log for the selected
        // vehicle. The log displays their info in a jTable using the AbstractTableModel:
        fileName = vehicleCB.getSelectedItem().toString();
        currentVehicle = vehicleCB.getSelectedItem().toString();

        if (!holdingList.isEmpty()) {
            holdingList.clear();
        }
        holdingList.addAll(tableFactory.createTable(AbstractTableFactory.TableType.MAINTENANCE, fileName));
        myModel.newDataNewTable(holdingList);
        maintTable.setModel(myModel);
        myModel.fireTableDataChanged();

        String[] makeModelYear = fileFacade.returnMakeModelYear("vehicleList", currentVehicle);
        userTextField.setText(currentUser);
        makeTextField.setText(makeModelYear[0]);
        modelTextField.setText(makeModelYear[1]);
        yearTextField.setText(makeModelYear[2]);

        loginPanel.setVisible(false);
        vehiclePanel.setVisible(false);
        maintenanceLogPanel.setVisible(true);
    }//GEN-LAST:event_goToLogButtonActionPerformed

    private void createNewVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewVehicleButtonActionPerformed
        // Button for creating new vehicle info:
        if (newMakeTB.getText().isEmpty() || newModelTB.getText().isEmpty() || newYearTB.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter text for all three fields.");
        } else {
            String newMake = newMakeTB.getText().toString();
            String newModel = newModelTB.getText().toString();
            String newYear = newYearTB.getText().toString();
            String[] newVehicleRow = {newMake, newModel, newYear, currentUser};
            fileFacade.writeNewVehicle("vehicleList", newVehicleRow);

            String[] tempVehicleRow = fileFacade.getUserVehicleList("vehicleList", currentUser);
            vehicleCB.removeAllItems();
            for (int i = 0; i < tempVehicleRow.length; i++) {
                vehicleCB.addItem(tempVehicleRow[i]);
            }
            fileFacade.writeBlankFile(newModel);

            newMakeTB.setText("");
            newModelTB.setText("");
            newYearTB.setText("");
        }
    }//GEN-LAST:event_createNewVehicleButtonActionPerformed

    private void vehicleLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleLogOutButtonActionPerformed
        // Log out button to take user back to login page from virtual garage page:
        loginPanel.setVisible(true);
        vehiclePanel.setVisible(false);
        maintenanceLogPanel.setVisible(false);
    }//GEN-LAST:event_vehicleLogOutButtonActionPerformed

    private void addRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowButtonActionPerformed
        // Adds the information from the text fields to the table:
        if (dateTB.getText().isEmpty() || milesTB.getText().isEmpty() || maintTB.getText().isEmpty()
                || commentsTB.getText().isEmpty() || costTB.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter text for all fields.");
        } else {
            TableData newMaintRow = new MaintenanceData(dateTB.getText(),
                    milesTB.getText(), maintTB.getText(), commentsTB.getText(), costTB.getText());
            myModel.addRow(newMaintRow);
            dateTB.setText("");
            milesTB.setText("");
            maintTB.setText("");
            commentsTB.setText("");
            costTB.setText("");
        }
    }//GEN-LAST:event_addRowButtonActionPerformed

    private void clearTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTextButtonActionPerformed
        // Clears text if needed:
        dateTB.setText("");
        milesTB.setText("");
        maintTB.setText("");
        commentsTB.setText("");
        costTB.setText("");
    }//GEN-LAST:event_clearTextButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Users must save their tables when done with them:
        fileName = currentVehicle;
        fileFacade.writeMaintenanceLog(fileName, myModel.getTableData());
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backGarageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backGarageButtonActionPerformed
        // Takes user back to their virtual garage:
        loginPanel.setVisible(false);
        vehiclePanel.setVisible(true);
        maintenanceLogPanel.setVisible(false);
    }//GEN-LAST:event_backGarageButtonActionPerformed

    private void maintLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintLogOutButtonActionPerformed
        // Takes user back to login screen, loggin them out:
        loginPanel.setVisible(true);
        vehiclePanel.setVisible(false);
        maintenanceLogPanel.setVisible(false);
    }//GEN-LAST:event_maintLogOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirtualGarageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirtualGarageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirtualGarageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirtualGarageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VirtualGarageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRowButton;
    private javax.swing.JButton backGarageButton;
    private javax.swing.JButton clearTextButton;
    private javax.swing.JTextField commentsTB;
    private javax.swing.JTextField costTB;
    private javax.swing.JButton createNewUserButton;
    private javax.swing.JButton createNewVehicleButton;
    private javax.swing.JTextField dateTB;
    private javax.swing.JButton goToLogButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton maintLogOutButton;
    private javax.swing.JTextField maintTB;
    private javax.swing.JTable maintTable;
    private javax.swing.JPanel maintenanceLogPanel;
    private javax.swing.JTextField makeTextField;
    private javax.swing.JTextField milesTB;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField newMakeTB;
    private javax.swing.JTextField newModelTB;
    private javax.swing.JTextField newPasswordTB;
    private javax.swing.JTextField newUsernameTB;
    private javax.swing.JTextField newYearTB;
    private javax.swing.JPasswordField passwordTB;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField userTextField;
    private javax.swing.JComboBox usernameCB;
    private javax.swing.JComboBox vehicleCB;
    private javax.swing.JButton vehicleLogOutButton;
    private javax.swing.JPanel vehiclePanel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
